language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("SloanDigitalSkySurvey"); Pkg.test("SloanDigitalSkySurvey"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("SloanDigitalSkySurvey")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
